### ISSUE TITLE
CGV

### ISSUE THREAD

**Issue by petri3** [philazerty/rubis#2]
Si on ajoute  "cgv.pdf" a  "rubis"  propale , la pied de page , ce mélange avec la fin du texte. 
Même problème si on ajoute des "Mention complémentaire sur les propositions commerciale" . 
<img width="724" alt="Screenshot 2024-03-08 130008" src="https://github.com/philazerty/module_rubis/assets/26501479/3cad1f59-e7e6-41bc-aa27-f6050b51c85a">.

dolibarr 18.0.5 
module rubis 17.0

**Comment by philazerty** [comment]
Pas de souci avec ma version 17 de Rubis. Github contient une v11
