### ISSUE TITLE
deposit  apparait sans raison

### ISSUE THREAD

**Issue by petri3** [philazerty/rubis#3]
Si j'ajoutes l'attribut supplémentaire tels que décrit dans "https://wiki.dolibarr.org/index.php?title=Module_Rubis_(FR)"

Il apparait sans raison dans le document 
<img width="718" alt="Screenshot 2024-03-08 130509" src="https://github.com/philazerty/module_rubis/assets/26501479/6566c5db-03d8-4de1-be01-627e064f2a62">

dolibarr 18.0.5 
module rubis : 17.0

**Comment by philazerty** [comment]
Pas de souci sur Rubis v17
