### ISSUE TITLE
N° d'engagement  et N° de marché : "BadValueForParamExtraFieldsObjectKey"

### ISSUE THREAD

**Issue by petri3** [philazerty/rubis#4]
Lors de la génération d'un propale "rubis" les mentions 
"N° d'engagement : BadValueForParamExtraFieldsObjectKeyN° de marché : BadValueForParamExtraFieldsObjectKey"
Apparaissent. 

J'ai trouvé comme workaround pour le moment de commenter la fonction ligne 480 			
```
	//include DOL_DOCUMENT_ROOT.'/custom/rubis/includes/rubis_add_chorus.inc.php';
```
dans le fichier "DOC_ROOT/custom/rubis/core/modules/propale/doc/pdf_rubis.modules.php"

dolibarr 18.0.5
module rubis 17.0

**Comment by philazerty** [comment]
Bonjour, 
Arrêtez de chercher, le code disponible sur Github n'est juste pas bon. C'est une version 11 ou presque. En fait je n'utilise pas GitHub.
Regardez sur https://www.dolibarr.fr/forum/t/rubis-pack-de-modeles-avec-cgv-etc/14646 et vous aurez réponses à vos soucis.
La version 17 devrait sortir ce mois ci.
@+

**Comment by philazerty** [comment]
Merci en tout cas pour votre participation. 
@+
